---
# file: roles/ntp/tasks/main.yml
# tasks file for ntp

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Set the correct timezone.
  file: path=/etc/localtime src="/usr/share/zoneinfo/{{ ntp_timezone }}" state=link force=yes
  tags: ntp

- name: Install NTP (RedHat).
  yum: name=ntp state=installed
  when: ansible_os_family == 'RedHat'

- name: Be sure ntp is configured
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd

- name: Ensure NTP is running and enabled at system start.
  service:
    name: "{{ ntp_daemon }}"
    state: started
    enabled: yes
  when: ntp_enabled

- name: Ensure NTP is stopped and disabled at system start.
  service:
    name: "{{ ntp_daemon }}"
    state: stopped
    enabled: no
  when: not ntp_enabled
